// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// c_unqlite_open
Rcpp::List c_unqlite_open(std::string dbfilename);
RcppExport SEXP _runqlite_c_unqlite_open(SEXP dbfilenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type dbfilename(dbfilenameSEXP);
    rcpp_result_gen = Rcpp::wrap(c_unqlite_open(dbfilename));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_runqlite_c_unqlite_open", (DL_FUNC) &_runqlite_c_unqlite_open, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_runqlite(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
